name: CI
on:
  push: {branches: [main]}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m venv .venv && source .venv/bin/activate && pip install -U pip && pip install -e . && pip install pytest
      - run: source .venv/bin/activate && pytest