name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pytest

      - name: Run unit tests
        run: |
          pytest tests/unit

      - name: Run e2e tests
        run: |
          pytest tests/e2e
        env:
          IACSEC_MODEL_CACHE: "${{ runner.temp }}/iacsec-model-cache"

      - name: Run action to produce SARIF
        uses: ./
        with:
          path: examples/sample_repo
          tech: ansible
          sarif_out: artifacts/ci-iacsec.sarif
          model_cache: "${{ runner.temp }}/iacsec-model-cache"

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: iacsec-scan
          path: artifacts/ci-iacsec.sarif
